### ISSUE TITLE
Redo performance profiling

### ISSUE THREAD

**Issue by bovee** [onecodex/needletail#15]
With the 0.2.0 rewrite we've probably changed our performance slightly (although I've run the benchmarks against both and they're very comparable). I removed the section we have in the README until we can benchmark our performance against readfq and Biopython again and maybe rust-bio? (and pfasta? See issue #2 ).

**Comment by kloetzl** [comment]
If you plan on releasing some new performance stats, definitely compare against the latest kseq. With a [recent patch](https://github.com/lh3/seqtk/pull/123) it now parses up to 2GB/s on a good machine with some tailwind.

**Comment by bovee** [comment]
For 0.3.0 I redid the benchmarks with criterion and added benchmarks against other Rust FASTX parsers so I think this is closed.

Note that our microbenchmark performance now seems to be heavily biased on the buffer size; we see best performance with a buffer size of 256kb on large (~Gb) files, but suffer on the microbenchmarks where a buffer size of 8-16kb seems to be optimal.
