### ISSUE TITLE
Bump to CircleCI 2.0 format

### ISSUE THREAD

**Issue by boydgreenfield** [onecodex/needletail#16]
Yes, this is a pain... but we only have 10 days :frowning:

**Comment by bovee** [comment]
Ugh, there's a whole Dockerfile buld process required now? Looks like there's some documentation at:

https://abronan.com/building-a-rust-project-on-circleci/

**Comment by Keats** [comment]
Done now, can anyone close?

**Comment by boydgreenfield** [comment]
@Keats Sorry about that, looks like this wasn't assigned to give the Core team write permissions. Fixed so you can close issues too. :)
