### ISSUE TITLE
Relax unicode requirement on header lines

### ISSUE THREAD

**Issue by bovee** [onecodex/needletail#29]
We just hit this where a file with a `\xA0` character (probably a Windows-1252 nonbreaking space?) broke. See Twitter thread for "community" consensus that this is basically impossible to require: https://twitter.com/shfo/status/1166054401376542721

So we probably shouldn't enforce this at file-parse time, but rather upstream if we need to (kind of like how we don't allow tabs in headers in some of our upstream processing code). This may slightly improve our benchmark performance since some reasonably large percentage of time (10%?) is spent validating UTF8.

**Comment by Keats** [comment]
Could needletail have the concept of coercions like the proxy? 2 modes: normal and strict. `normal` errors on tabs and other invalid characters while `strict` replaces tab by `|` and removes non utf8 errors. Same thing for non atcg bases replacement.

This way, it opens the way to using needletail in the proxy

**Comment by bovee** [comment]
We're no longer enforcing UTF8 in headers as of 4aef928bee0d83c8df6bdf52e838399818e12444.
