### ISSUE TITLE
SequenceRecord is not intuitive

### ISSUE THREAD

**Issue by bovee** [onecodex/needletail#38]
We had a user who had an issue creating a `Vec<SequenceRecord>` and then appending the `SequenceRecord` from inside the `parse_sequence_reader` callback. This doesn't work because the `SequenceRecord` itself has data borrowed for only the lifetime of that function call.

We should:
 - Probably document the lifetime semantics of `SequenceRecord` a little better so it's clearer why the callback is there in the first place?
 - Add a method to turn a `SequenceRecord` into an owned version of itself. Right now this is kind of gross to do manually, e.g. `let copied_seq = SequenceRecord::new(Cow::from(seq.id.into_owned()), Cow::from(seq.seq.into_owned()), seq.qual.map(|q| Cow::from(q.into_owned())));` so we should add a convenience method to improve ergonomics.

**Comment by Keats** [comment]
It changed significantly so closing.
