### ISSUE TITLE
Example for type_callback

### ISSUE THREAD

**Issue by mbhall88** [onecodex/needletail#43]
It would be great if there was an example of how to use the `type_callback` in [`parse_sequence_path`](https://docs.rs/needletail/0.3.2/needletail/formats/fn.parse_sequence_path.html). Even after looking at the source code it isn't obvious to me what can be done with this callback?

**Comment by Keats** [comment]
We only use it once in our codebase afaik, to `panic` in a CLI if the file is not of the excepted type.

**Comment by mbhall88** [comment]
Could you possibly add an example of that to the docs when you get the time?

**Comment by mbhall88** [comment]
Found an example in a test here https://github.com/onecodex/needletail/blob/e5969cd826420653869266be1901962c0dfd43ab/src/formats/fastq.rs#L327-L330

**Comment by bovee** [comment]
I believe it was added to allow a post-process script to know what the file type was so the full headers could be reconstructed (e.g. adding the @ or > back in front of every header when they're written out).

**Comment by mbhall88** [comment]
Makes sense :+1:
