### ISSUE TITLE
buf_redux not maintained and unsupported in future version

### ISSUE THREAD

**Issue by jianshu93** [onecodex/needletail#64]
Hello Team,

See an issue here:  https://github.com/abonander/buf_redux/issues/23

Since the original version is not maintained anymore (archived) and it will not be supported due to the error mentioned above. There is an drop in replacement for it and fix the issue: https://crates.io/crates/buffer-redux 

Everything else should be exactly the same. Can you please quickly publish a version to crate so that we can avoid the error when using needletail?

Thanks,

Jianshu

**Comment by Keats** [comment]
I didn't see there was a replacement crate! I was planning to tackle this issue next week anyway.

**Comment by jianshu93** [comment]
Many thanks and this is very fast!
