### ISSUE TITLE
how to retrieve file format(Fasta or Fastq) in Reader?

### ISSUE THREAD

**Issue by wjwei-handsome** [onecodex/needletail#66]
As stated in the title, how can I get the determined reader struct(FastaReader or FastqReader) type after `parse_fastx_file(my_file)` .

I don't seem to find such an API, so came to seek your help.

Thanks!

**Comment by Keats** [comment]
You can use https://docs.rs/needletail/latest/needletail/parser/struct.SequenceRecord.html#method.format but it's on the sequence record you get when you iterate, not on the parser.

**Comment by wjwei-handsome** [comment]
> You can use https://docs.rs/needletail/latest/needletail/parser/struct.SequenceRecord.html#method.format but it's on the sequence record you get when you iterate, not on the parser.

Thanks, i got it.

Best wishes.
