### ISSUE TITLE
Support for zstd

### ISSUE THREAD

**Issue by mbhall88** [onecodex/needletail#71]
Hi,

I would be great if the compression feature could also support zstd compression.

**Comment by audy** [comment]
Hi @mbhall88, we would accept a PR from your branch but can you add an feature flag specifically for zstd (as was added in https://github.com/onecodex/needletail/pull/77/files#diff-fc6a8d66b8cb6bd48a119a70e489cbcef82e7f551e7cf08e8e972ef4e774ef49R10)?
