### ISSUE TITLE
Integrate "Honor individual compression features" into a release

### ISSUE THREAD

**Issue by PB-DB** [onecodex/needletail#79]
Hi,

This is a very useful library.

It's great that as of https://github.com/onecodex/needletail/commit/08101cb304ba0431ad4f718e7a065bf51ff6f8d1, the repository honors compression features.

I'm currently pointing to the most recent commit in my work, as 0.5.1 is the latest crate available and it does not include this fix. It would be nicer to use an official crate version instead.

I'm sure you're working on additional features to release, so I understand it may take time.

I look forward to using it when it's available.

Thanks!

**Comment by audy** [comment]
@PB-DB this is included in 0.6.0 published on crates.io
