### ISSUE TITLE
Tests are missing from crate

### ISSUE THREAD

**Issue by mr-c** [onecodex/needletail#81]
Hello, I'm packaging needletail for Debian, and I see that this repo has a bunch of tests missing from https://crates.io/crates/needletail

Can they be included in the next release?

Thanks

**Comment by audy** [comment]
@mr-c I'm not familiar with Debian packaging. What do we need to do on our end (just merge and push a new release to Cargo)?

Is your goal to package Needletail as a Rust library or as a Python package?

**Comment by mr-c** [comment]
> Is your goal to package Needletail as a Rust library or as a Python package?

Currently just as a rust library, as it is a dependency of https://github.com/sourmash-bio/sourmash/
