### ISSUE TITLE
New version in crates.io

### ISSUE THREAD

**Issue by tmaklin** [onecodex/needletail#85]
Hi, I'm using needletail in a Rust project that targets WebAssembly but the current version in crates.io (0.5.1) does not compile for wasm unless the compression feature is disabled because of some issues with bzip2 and xz.

It would be great if the version in crates.io could be updated to contain the [honor individual compression features](https://github.com/onecodex/needletail/commit/08101cb304ba0431ad4f718e7a065bf51ff6f8d1) changes so that the flate2 compression feature can be kept while disabling others without manually patching the crate. Thanks for maintaining this package!

**Comment by audy** [comment]
@tmaklin we've pushed an updated version to crates.io https://crates.io/crates/needletail/0.6.0.

Let me know if this resolves the issue.

**Comment by tmaklin** [comment]
Thank you @audy for the very quick response! All good now.
